name: Deploy Build

on:
  push:
    branches:
      - stable

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Clone game assemblies from private repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/KaBooMa/ScheduleOneAssemblies.git ./ScheduleOneAssemblies

      - name: Restore .NET dependencies
        run: dotnet restore

      # Install Node.js and semantic-release
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install semantic-release via NPM
        run: |
          npm install -g semantic-release

      # Run semantic-release to handle versioning, changelog, and release
      - name: Run semantic-release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'stable'
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Update MelonInfo version for S1API and S1APILoader
        run: |
          sed -i "s/{VERSION_NUMBER}/${{ steps.semantic-release.outputs.new_release_version }}/" ./S1API/S1API.cs
          sed -i "s/{VERSION_NUMBER}/${{ steps.semantic-release.outputs.new_release_version }}/" ./S1APILoader/S1APILoader.cs

      - name: Run .NET build for MonoBepInEx
        run: dotnet build ./S1API.sln -c MonoBepInEx -f netstandard2.1

      - name: Run .NET build for Il2CppBepInEx
        run: dotnet build ./S1API.sln -c Il2CppBepInEx -f net6.0

      - name: Run .NET build for MonoMelon
        run: dotnet build ./S1API.sln -c MonoMelon -f netstandard2.1

      - name: Run .NET build for Il2CppMelon
        run: dotnet build ./S1API.sln -c Il2CppMelon -f net6.0
        
      - name: Build artifact zip for Thunderstore
        run: |
          mkdir -p ./artifacts/thunderstore/Plugins
          mkdir -p ./artifacts/thunderstore/Mods
          cp ./S1APILoader/bin/MonoMelon/netstandard2.1/S1APILoader.dll ./artifacts/thunderstore/Plugins/S1APILoader.MelonLoader.dll
          cp ./S1APILoader/bin/MonoBepInEx/netstandard2.1/S1APILoader.dll ./artifacts/thunderstore/Plugins/S1APILoader.BepInEx.dll
          cp ./S1API/bin/Il2CppMelon/net6.0/S1API.dll ./artifacts/thunderstore/Mods/S1API.Il2Cpp.MelonLoader.dll
          cp ./S1API/bin/MonoMelon/netstandard2.1/S1API.dll ./artifacts/thunderstore/Mods/S1API.Mono.MelonLoader.dll
          cp ./S1API/bin/Il2CppBepInEx/net6.0/S1API.dll ./artifacts/thunderstore/Mods/S1API.Il2Cpp.BepInEx.dll
          cp ./S1API/bin/MonoBepInEx/netstandard2.1/S1API.dll ./artifacts/thunderstore/Mods/S1API.Mono.BepInEx.dll
          
      - name: Publish artifact to Thunderstore
        uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: KaBooMa
          description: A Schedule One Mono / Il2Cpp Cross Compatibility Layer
          token: ${{ secrets.TS_TOKEN }}
          name: S1API
          repo: thunderstore.io
          version: ${{ steps.semantic-release.outputs.new_release_version }}
          community: schedule-i
          icon: https://raw.githubusercontent.com/KaBooMa/S1API/stable/Public/logo_compressed.png
          readme: https://raw.githubusercontent.com/KaBooMa/S1API/stable/Public/README.md
          deps: LavaGang-MelonLoader@0.7.0
          path: artifacts/thunderstore
          categories: |
            mono
            il2cpp
            libraries

      - name: Pack NuGet package
        run: dotnet pack ./S1API/S1API.csproj -c MonoMelon --output ./nupkg /p:PackageVersion=${{ steps.semantic-release.outputs.new_release_version }}
        
      - name: Push to NuGet Gallery
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
